name: CodeQL

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/analyze.yml
      - .github/workflows/cancel.yml
      - .github/workflows/release.yml
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  schedule:
    - cron: '42 10 * * 4'

jobs:
  build:
    uses: opengoodio/central-workflows/.github/workflows/codeql-analyze.yml@main
