name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/cancel.yml
      - .github/workflows/release.yml
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengoodio/central-workflows/.github/workflows/gradle-lib-build.yml@main
    with:
      run-gradle-validation: true
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
