name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: opengoodio/central-workflows/.github/workflows/gradle-lib-release.yml@main
    secrets:
      git-email: ${{ secrets.GIT_EMAIL }}
      git-user: ${{ secrets.GIT_USER }}
      gpg-signing-password: ${{ secrets.GPG_SIGNING_PASSWORD }}
      gpg-signing-private-key: ${{ secrets.GPG_SIGNING_PRIVATE_KEY }}
      oss-repo-username: ${{ secrets.OSS_REPO_USERNAME }}
      oss-repo-password: ${{ secrets.OSS_REPO_PASSWORD }}
