name: updater
# description:
# - Runs on a schedule to automatically update GitHub action versions
on:
  workflow_dispatch:
  schedule:
    # Automatically run every Sunday
    - cron:  '0 0 * * 0'

jobs:
  updater:
    name: Run Update GitHub Action Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update GitHub Action Versions
        uses: saadmk11/github-actions-version-updater@v0.5.6
        with:
          committer_username: ${{ secrets.CI_USER_GIT_USER }}
          committer_email: ${{ secrets.CI_USER_GIT_EMAIL }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ignore: '["actions/checkout@v2", "actions/cache@v2"]'